# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64)),
                ('publication_date', models.DateTimeField()),
                ('category', models.CharField(max_length=64)),
                ('hero_image', models.ImageField(upload_to='')),
                ('opt_image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
