# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    replaces = [('articles', '0002_auto_20161124_0607'), ('articles', '0003_auto_20161124_0617'), ('articles', '0004_auto_20161127_1306')]

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='hero_imgs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='opt_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publication_date',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(upload_to='article/hero_imgs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='opt_image',
            field=models.ImageField(blank=True, null=True, upload_to='article/opt_imgs'),
        ),
    ]
