# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 06:07
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='hero_imgs'),
        ),
    ]
