# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20161124_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='opt_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
