# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20161124_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publication_date',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(upload_to='article/hero_imgs'),
        ),
        migrations.AlterField(
            model_name='article',
            name='opt_image',
            field=models.ImageField(blank=True, null=True, upload_to='article/opt_imgs'),
        ),
    ]
